name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create build directory
        run: |
          mkdir -p dist
          cp -r api dist/
          cp -r static dist/ || true
          cp -r templates dist/ || true
          cp manage.py dist/
          cp requirements.txt dist/

      - name: Initialize Database
        run: |
          cd dist
          python manage.py createdb

      - name: Start Application
        env:
          FLASK_APP: manage.py
          FLASK_ENV: production
        run: |
          cd dist
          python manage.py runserver --host=0.0.0.0 --port=8000

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish dist --project-name=your-project-name
